[project]
name = "pyfuze"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Tanix", email = "tanixlu@foxmail.com" }
]
requires-python = ">=3.8"
dependencies = []

[project.scripts]
pyfuze = "pyfuze.cli:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
include = [
    "pyfuze/**",
]
