[project]
name = "pyfuze"
version = "0.2.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Tanix", email = "tanixlu@foxmail.com" }
]
requires-python = ">=3.8"
dependencies = [
    "rich>=14.0.0",
    "typer>=0.15.3",
]

[project.scripts]
pyfuze = "pyfuze.cli:app"

[build-system]
requires = ["uv_build>=0.7.3,<0.8"]
build-backend = "uv_build"

[[tool.uv.index]]
url = "https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple"
default = true
