[project]
name = "complex"
version = "0.1.0"
requires-python = ">=3.8"
dependencies = [
    "pyside6>=6.6.3.1; sys_platform == 'win32'",
    "packaging>=25.0; sys_platform == 'win32'",
    "distro>=1.9.0; sys_platform != 'win32'",
]
